version: '3.6'

services:
  db:
    image: postgres:11.1-alpine
    volumes:
      - ./.data/pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
